site_name: DBI-Project MKdocs
site_description: Project for 2 semester for Webudhvilker - MKdocs
site_author: Anders, Claudia og Isabella

theme:
  name: material #Eller readthedocs som navn

nav:
  - StartSide: index.md
  - Git: git.md
  - Clean Code: cleanCode.md
  - Test: test.md
